version: '3'
services:
  app:
    image: khalidbfn/masarat_app:v1.0
    #build:
      #context: .
      #dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - /app/node_modules
      - .:/app
